name: Web E2E Tests

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # clone do projeto para a máquina
      - uses: actions/checkout@v4

      # conferir a versão instalada
      - name: Node version
        run: node --version

      - name: Instalando dependências
        run: npm install

      - name: Executando os spec automation-exercise.modules.cy.js
        run: npm run cy:run -- --spec "cypress/e2e/automation-exercise.modules.cy.js"

      - uses: actions/upload-artifact@v4
        # Garante que os artefatos sejam sempre enviados, mesmo se os testes falharem
        if: always()
        with:
          name: relatorios
          path: |
            cypress/videos
            cypress/screenshots
            cypress/reports   
